name: build and deploy pelican outputs

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: pip install pelican markdown beautifulsoup4 pelican-series pelican-sitemap
      - run: pelican content
      - run: echo "blog.tykl.me" >> output/CNAME
      - run: echo "" >> output/.nojekyll
      - run: cp -f ./robots.txt ./output/robots.txt
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree output add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh_pages --force

